### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by aamit2267** [SpectrixOfficial/discordpy-dialogflow-chatbot#1]
I am not getting any response. Response is an type of error. How can i fix it. [Output image](https://cdn.discordapp.com/attachments/737597752287952926/737917114756890705/IMG_20200729_114759.jpg)

**Comment by SpectrixDev** [comment]
This is either an error on dialogflow's side with their api, or you're possibly using dialogflowv2. This code seems to only work with dialogflowv1.

**Comment by amit-agarwal2267** [comment]
Can you share the other code i waana make a ai chat bot for my server members. Please

**Comment by amit-agarwal2267** [comment]
@SpectrixOfficial i used v2 key no error now but still bot not responding

**Comment by SpectrixDev** [comment]
Try using a V1 agent instead. If you want to try using v2, refer to this https://github.com/googleapis/dialogflow-python-client-v2
